### ISSUE TITLE
[Bug] Staticman comment error

### ISSUE THREAD

**Issue by VincentTam** [einsteinpy/blog.einsteinpy.org#12]
# Error encountered

A `GITHUB_READING_FILE` error.

![Screenshot_2019-05-29 Yayy We have applied to SOCIS ](https://user-images.githubusercontent.com/5748535/58569135-d29ea280-8235-11e9-94f0-96858e6f2682.png)

# :construction_worker_man: Staticman Configurations for Beautiful Jekyll

:email: Please don't hesitate to ping me on GitHub/GitLab/leave a comment on my blog/send me an email to ask for help.

1. :checkered_flag: Invite @staticmanlab as a collaborator to your repository (by going to your repository Settings page, navigate to the Collaborators tab).  
![send invitation to Staticman Lab](https://git.io/fjZPx)  
Image short link: https://git.io/fjZPx
2. :ballot_box_with_check: Help @staticmanlab accept the invitation by going to

        https://staticman3.herokuapp.com/v3/connect/github/<username>/<repo-name>

    In your case, that's

        https://staticman3.herokuapp.com/v3/connect/github/einsteinpy/einsteinpy.github.io

    ![Staticman Lab invitation accepted](https://camo.githubusercontent.com/fca08dcc33537c78f0b56e934afde4af0605f706/68747470733a2f2f76696e63656e7474616d2e6769746c61622e696f2f706f73742f323031382d31322d31392d7374617469636d616e2d696e7669746174696f6e2d69732d636173652d73656e7369746976652f696e76697465322e706e67)  
    Figure: image showing setup for [my fork of this theme](//git.io/bjsm0)  
    Image short link: https://git.io/fjZXG

    ![Staticman Lab shown as collaborator](https://camo.githubusercontent.com/eb3d86ecf35497912c485fb2d339d9d3cd962197/68747470733a2f2f76696e63656e7474616d2e6769746c61622e696f2f706f73742f323031382d31322d31392d7374617469636d616e2d696e7669746174696f6e2d69732d636173652d73656e7369746976652f696e76697465332e706e67)  
    Figure: @staticmanlab invited to GitHub repo  
    Image short link: https://git.io/fjZXZ

3. :writing_hand: Fill in your `repository` and `branch` in the Staticman section of `_config.yml`.

    ```yml
     # Staticman support 
     staticman: 
       repository : "<username>/<repo-name>" # GitHub username/repository eg. "daattali/beautiful-jekyll" 
       branch     : "master" # eg. "master" If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml` 
       endpoint   : # URL of your own deployment (with trailing slash) (will fallback to a public GitLab instance) 
       reCaptcha: 
         # reCaptcha for Staticman (OPTIONAL) 
         # If you use reCaptcha, you must also set these parameters in staticman.yml 
         siteKey  : # Use your own site key, you need to apply for one on Google 
    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret> 
    ```

4. :memo: Start commenting.
